trying build mypy-cross for all versions

diff --git a/.github/workflows/cp-versions.yml b/.github/workflows/cp-versions.yml
--- a/.github/workflows/cp-versions.yml
+++ b/.github/workflows/cp-versions.yml
@@ -28,7 +28,21 @@ jobs:
       - name: Determine mpy-cross versions
         id: get_cp_versions
         run: |
-          # Call the function directly from a Python script.
+          # Execute the script and capture the output
           versions=$(python mpy_cross_circuit/versions.py)
-          echo "MPY_VERSIONS=$versions" >> $GITHUB_ENV
-          echo "::set-output name=all_versions::$versions" # Set output for other jobs
+
+          # Print the raw output for debugging
+          echo "Raw output: $versions"
+
+          # Check if the output is empty
+          if [ -z "$versions" ]; then
+            echo "Error: No versions found by mpy_cross_circuit/versions.py"
+            exit 1
+          fi
+          # Split the output into an array, handling potential newlines
+          IFS=' ' read -r -d '' -a versions_array <<< "$versions"
+
+          # Join the array elements with spaces
+          versions_string=$(IFS=' '; echo "${versions_array[*]}")
+          echo "MPY_VERSIONS=$versions_string" >> $GITHUB_ENV
+          echo "::set-output name=all_versions::$versions_string"
